<a href="https://colab.research.google.com/github/leonaardobrito/data-mining/blob/main/Exemplo_MLP_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Exemplo MLP - Classificação de flores
Disciplina de Data Mining - INE5644


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

###Carrega o conjunto de dados

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)

In [ ]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
X = dataset.iloc[:, :-1].values
y = pd.DataFrame(dataset.iloc[:, 4].values,columns=['Class'])
y.head()

Class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [ ]:
from sklearn import preprocessing
#label encoder - categórico para numérico - sklearn converte para one hot encoding internamente
le = preprocessing.LabelEncoder()
y = y.apply(le.fit_transform)
y

Class
0        0
1        0
2        0
3        0
4        0
..     ...
145      2
146      2
147      2
148      2
149      2

[150 rows x 1 columns]

###Divide em treino e teste

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,stratify=y,random_state=99)

### Padroniza (z-score) os dados  (feature scaling)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

##Constrói o modelo

In [ ]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(2,2),max_iter=3000,random_state=171)
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(2, 2), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=3000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=171, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

###Realiza a predição e a avaliação do modelo

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = mlp.predict(X_test)

cm=confusion_matrix(y_test,y_pred)

print(cm)
print(classification_report(y_test,y_pred))

[[16  0  0]
 [17  0  0]
 [17  0  0]]
              precision    recall  f1-score   support

           0       0.32      1.00      0.48        16
           1       0.00      0.00      0.00        17
           2       0.00      0.00      0.00        17

    accuracy                           0.32        50
   macro avg       0.11      0.33      0.16        50
weighted avg       0.10      0.32      0.16        50



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#exemplo de busca de hiper-parâmetros usando Cross-Validation
from sklearn.model_selection import cross_val_score

test_arch = [(1,3),(1,5,2),(3,3),(5,1),(1,5)]

for arch in test_arch:
    print(f"Testando arquitetura {arch}")
    model = MLPClassifier(hidden_layer_sizes=arch, random_state=1, max_iter=2000)
    accuracy = cross_val_score(model, X_train, y_train.values.ravel(), cv = 10)
    print(accuracy)
    print("Acuracia media: ",accuracy.mean())

Testando arquitetura (1, 3)
[0.7 0.7 0.7 0.6 0.6 0.6 0.7 0.7 0.7 0.7]
Acuracia media:  0.6699999999999999
Testando arquitetura (1, 5, 2)
[0.6 0.6 0.6 0.6 0.6 0.6 0.7 0.7 0.7 0.8]
Acuracia media:  0.65
Testando arquitetura (3, 3)
[1.  0.9 0.9 1.  0.8 1.  0.9 1.  1.  1. ]
Acuracia media:  0.95
Testando arquitetura (5, 1)
[0.3 0.3 0.3 0.3 0.3 0.3 0.4 0.4 0.4 0.4]
Acuracia media:  0.33999999999999997
Testando arquitetura (1, 5)
[0.6 0.6 0.6 0.7 0.7 0.8 0.7 0.7 0.7 0.8]
Acuracia media:  0.6900000000000001


baseado no exemplo apresentado em: https://stackabuse.com/introduction-to-neural-networks-with-scikit-learn/